###########
# site.title, site.author.name

title:  基于Bert的同义句训练
author:
  name: Terry Chan

########
# more settings

collections:
  chapters:
      output: false

markdown: kramdown

kramdown:
  auto_ids: true


sass:
  sass_dir: css
  style:    expanded


exclude:
- README.md


safe: true
lsi: false
